#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Supply name of file to compile"
else
  filename="$1"
fi

#Name of compiled file -use filename
outfile=${filename%.*}
echo $outfile
#Name of compiler
fc=gfortran
cflags="-g -std=f2003 -Wall"

#Actual compile line. Other flags etc can be added
$fc $cflags $filename -o $outfile
